FROM ubuntu:20.04

# Instala dependencias necesarias
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-tk \
    libglib2.0-0 \
    x11-apps \
    x11vnc \
    xvfb \
    fluxbox \
    && rm -rf /var/lib/apt/lists/*

# Instala las dependencias de Python
COPY requirements.txt /app/
RUN pip3 install -r /app/requirements.txt

# Copia el código del proyecto
COPY . /app/
WORKDIR /app

# Inicia Xvfb, Fluxbox y x11vnc
CMD ["sh", "-c", "Xvfb :1 -screen 0 1024x768x16 & fluxbox & x11vnc -display :1 -nopw -listen localhost -xkb & python3 run.py"]

